### PR TITLE
Add alert functionality using VictorOps's REST API and a bug fix.

### PR DESCRIPTION
**Pull request by ncarlsonIteris**
Found a bug not allowing users to send multi-word messages. Additionally, allowed users to send alerts to the on-call team member(s). Testing was done using using an XMPP adapter for Hubot. Thanks,
Nathan

### CODE REVIEW

**Comment by jm-welch** [comment]
It looks like it was taken down from GitHub, but there used to be a (semi) official script from VOps that would create and route incidents from the interface. I'm still using it in my environment as a separate script, which is why I didn't cook it in here. Let's split it off into its own script, since who's on-call currently doesn't really matter for raising an incident.

Where was the bugfix for multi-word messages? I seem to recall having fixed that locally, but I probably forgot to push the fix live.

**Comment by jm-welch** [comment]
Check out vopage.coffee in the dev branch and see if that does what you'd expect. I'll be doing some testing against my sandbox soonish, to confirm that it all works as expected.

**Comment by ncarlsonIteris** [comment]
The fix was in the regular expression that hubot listens for when doing @!<team> message. Look at the "bugfix" branch of my fork. I will look at vopage.coffee

**Comment by ncarlsonIteris** [comment]
@!team\* message

**Comment by ncarlsonIteris** [comment]
vopage.coffee looks good. In the event of an error or failure to send an alert for any reason it would probably be appropriate to display the team members that are on call in case it is an emergency or if the person forgets the other command used in current.coffee. I suppose they would be aware of all the commands, but it might be a good idea. Additionally, the regular expressions should be altered to the format in the "bugfix" branch. I also realized I did not make a pull request for the bugfix branch, sorry for the confusion.

**Comment by jm-welch** [comment]
Do we still need this feature, in light of the new "Create Incident" option available natively in VictorOps?

**Comment by jm-welch** [comment]
As mentioned in the other PR, please issue against the Dev branch. I'll be combining multiple change s to update Master soon.

**Pull request closed without merging**
